databases:
  - name: tiendaderopa
    plan: free
    databaseName: tiendaderopa
    user: tiendaderopa_user

services:
  - type: web
    plan: free
    name: tiendaderopa
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn TiendaOficial.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tiendaderopa
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
